### ISSUE TITLE
Migrate to ExternalSystemTaskState

### ISSUE THREAD

**Issue by Unthrottled** [waifu-motivator/waifu-motivator-plugin#163]
We'll eventually want to migrate to the new task state API.

https://github.com/zd-zero/waifu-motivator-plugin/blob/c6728a8a02693771c99f4314f82acf95a367aa2b/src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java#L49

**Comment by zd-zero** [comment]
Right! Already forgot about this one, thanks for creating an issue.
