### ISSUE TITLE
Registered Post Startup Activities must be dumb aware 

### ISSUE THREAD

**Issue by Unthrottled** [waifu-motivator/waifu-motivator-plugin#219]
I was looking at the `idea.log` file and came across this nice little warning

```
2020-09-27 07:22:07,897 [  11860]   WARN - tartup.impl.StartupManagerImpl - Activities registered via registerPostStartupActivity must be dumb-aware: zd.zero.waifu.motivator.plugin.WaifuMotivatorProject$$Lambda$1490/0x000000010169ac40@4d824e93
```

**Comment by rubenquadros** [comment]
The `Runnable` should implement `DumbAware` but in our case `UserOnboarding` as an object. Do we make make a separate runnable and call `UserOnBoarding.attemptToPerformNewUpdateActions` in it? 

`UserOnBoarding.attemptToPerformNewUpdateActions` is also used in `PluginInstallListener`

**Comment by Unthrottled** [comment]
> Do we make make a separate runnable and call UserOnBoarding.attemptToPerformNewUpdateActions in it?

You can just make UserOnboarding implement `DumbAware` like the actions are:
https://github.com/waifu-motivator/waifu-motivator-plugin/blob/437cfd6f8181ff891062aa5267c649d45b820e0f/src/main/java/zd/zero/waifu/motivator/plugin/actions/ShowWaifuOfTheDayAction.java#L9

> is also used in PluginInstallListener

It's not the so much using the method as it is the function that is being submitted to the `runWhenProjectIsInitialized` function. That said I dunno if it's complaining about this runnable not being dumb aware:
https://github.com/waifu-motivator/waifu-motivator-plugin/blob/5218b82252cc26445f22a2c77461232a74dc2ac6/src/main/java/zd/zero/waifu/motivator/plugin/listeners/PluginInstallListener.kt#L26

**Comment by rubenquadros** [comment]
I ran the plugin and now I'm not getting this log in the `idea.log` file. Can you please check once as well?

**Comment by Unthrottled** [comment]
I'm not getting it either, Hurray fixing stuff by waiting! 🎉
