### ISSUE TITLE
Waifu profiler

### ISSUE THREAD

**Issue by zd-zero** [waifu-motivator/waifu-motivator-plugin#23]
This idea is to have a setting for different Waifu attitudes to not always motivate users as too much motivation would annoy them, there's a setting for that but I think that doesn't suffice as by adding some attitudes we could lessen the robotic feel.

We could have some options like the following:
'Tsundere' - there's a chance that instead of motivating you, she'll say bad things to you, and would be ruthless when your tests fail!
'Dandere' - only a small chance that your waifu will motivate you as she's shy.
etc.

We could extend this and have a possibility to have a different set of motivational assets for each waifu attitude.

**Comment by zd-zero** [comment]
The problem this issue tries to solve seems to be tackled by #106, so the plugin is not too annoying as having a profile for each platform will require us to provide more assets.

**Comment by Unthrottled** [comment]
I feel like if we enable to prefer motivations from a specific waifu, this might solve this issue.

#142 Enables us to group and show assets from a specific waifu.

Do you think we still need this?

**Comment by zd-zero** [comment]
Hmmmm, yes that'll solve the issue if they only like tsundere *Waifu*s they can pick it from the list, maybe we can have a way to categorize the *Waifu*s, wdyt?

**Comment by Unthrottled** [comment]
🤔 Yeah, I guess that makes senses. Rather than picking from a single waifu, just give me a specific type of waifu. I think it will make more sense to work this after grouping the assets by character (eg the work from #174)

**Comment by zd-zero** [comment]
I think this issue is now irrelevant as we already have WENDI in place, that solves the dry experience, and may conflict with it when this is implemented, with that said I'll close this for now.
