### ISSUE TITLE
Minimal Mode

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#239]
**Describe the user story**

As a user, I'd like to have a minimal mode where alerts should still show but not on repeating events whenever I'm doing TDD, repeating `success` and `failure` events occurs thus alerts are shown for every event.

**Describe the solution you'd like**

Only show an alert whenever the mood/category changes in that way I only get alerted in the event of multiple `failures` then going to a `passed` event.

**Additional context**

This is related to the [discussions](https://github.com/zd-zero/waifu-motivator-plugin/pull/238/files#r504553720) with
#238 of issue #106 

This story is similar to #231 that prevents all alerts to be shown, but this story is still showing alerts but in minimal occurrences.

<details>
<summary>Brain Dumps</summary>

Some quoted comments for quick context

> zd-zero: My main motivation is whenever a user works in a TDD environment, there would be a lot of multiple failures sequentially, so when a test passes it should now show an alert and vice versa. wdyt?

> Unthrottled: Rather than always counting the invocations, how about we have like a Minimal Mode. Where, for a brief period of time, we only receive an alert when the MotivationEventCategory changes (eg. test passing/failing, or fixing your broken build). After that period expires, then the plugin goes back to alerting to any event.
I've got more ideas about this, but I wanted to get your opinion on this, because it is a bit different than what was initially proposed. I actually have use-cases for this, and would like to have this implemented.

*You can [check more](https://github.com/zd-zero/waifu-motivator-plugin/pull/238/files#r504553720) from the PR #238*
</details>

**Comment by Unthrottled** [comment]
Moved issue over here https://github.com/Unthrottled/AMII/issues/70
