### ISSUE TITLE
Revamp Just-Your-Waifu interface

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#247]
**Describe the user story**

As a user, I want things to be grouped and organized and more intuitive.

**Describe the solution you'd like**

The solution is what we can find in `Tools | Diagrams`, this way the parent node would be the Anime and the child node would be the characters of that anime, so users can pick which anime group, not just for each *Waifu*. This would of course be one tree level down.

<img width="649" alt="Screen Shot 2020-10-22 at 05 44 12" src="https://user-images.githubusercontent.com/21978370/96790763-eef23f00-1429-11eb-92ef-1562152640ff.png">

**Additional context**

As we'll add more *Waifu* we should improve the interface grouped by their anime, so we wouldn't have a long list of *Waifu* from the settings.

<img width="751" alt="Screen Shot 2020-10-22 at 05 45 11" src="https://user-images.githubusercontent.com/21978370/96790959-31b41700-142a-11eb-88bb-1ef859ea7304.png">

```
v [ ] Kill La Kill
    [ ] Kiryuin Satsuki
    [ ] Matoi Ryuko
> [ ] Re-Zero
... 
```

Relates to: #174

**Comment by Unthrottled** [comment]
Currently working on being able to tag assets in the management dashboard, just wanted to get input on how best to support this. I've come up with this:

```typescript
export interface Anime {
  id: string;
  name: string;
}

export interface Waifu {
  id: string;
  name: string;
  animeId: string;
}

export interface VisualAssetDefinition {
  path: string;
  imageAlt: string;
  imageDimensions: ImageDimensions;
  categories: WaifuAssetCategory[];
  groupId?: string;
  characterIds?: string[]; // to support legacy versions of WMP is separate field 
  characters?: string[];
}
```

Where we would have character definitions defined in a separate file and just provide ids in the visual asset definitons (to reduce size of the visual asset definition payload)

**Comment by Unthrottled** [comment]
I've got some sample API responses for `non-prod`

**Waifu**
https://waifu-motivation-assets-nonprod.s3.amazonaws.com/waifu/list.json

**Anime**
https://waifu-motivation-assets-nonprod.s3.amazonaws.com/anime/list.json
