### ISSUE TITLE
Migrate string literals into message bundle

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#262]
The messages are scattered in the application and should be moved into the [message bundle](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/src/main/resources/messages/MessageBundle.properties), for future needs where we can apply i8n in the plugin.

e.g.
https://github.com/zd-zero/waifu-motivator-plugin/blob/ad13b4b06ac848a864d7f187da7a60299a1b4f5f/src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java#L74-L78

**Comment by anazari96** [comment]
Can I take this one? 
And if yes, Should I check whole the project or only fix this one ? :thinking:

**Comment by zd-zero** [comment]
> Can I take this one?

Sure ;)

> Should I check whole the project or only fix this one ? 🤔

Hmmm, it would be better if you can migrate all of the literals into the message bundle, so we can manage strings easier, as this would be used for i8n.

Thank you for your interest, if you're okay with it, I'll assign it to you 🤗

**Comment by anazari96** [comment]
Yes, It's my pleasure. :relaxed:

**Comment by Unthrottled** [comment]
>  as this would be used for i8n

@zd-zero Are there plans to internationalize the motivation title assets?

**Comment by zd-zero** [comment]
I think that it would be hard to maintain if we do it for the motivation assets as it contains emotions as we would be adding more of it, other users can still use the plugin even if they ignore the motivation titles, but for the settings, offline notifs, errs, etc. they need to understand it.

**Comment by Unthrottled** [comment]
I think I missed a couple literals in this project, for example:

- https://github.com/waifu-motivator/waifu-motivator-plugin/blob/e390574b24098197423e28908e59928ae64248f1/src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/DialogTipPanel.java#L41
- https://github.com/waifu-motivator/waifu-motivator-plugin/blob/e390574b24098197423e28908e59928ae64248f1/src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt#L49

**Comment by rubenquadros** [comment]
I can check for missing strings and add them to the message bundle

**Comment by Unthrottled** [comment]
@rubenquadros Go for it 👍
