### ISSUE TITLE
Idle Event input sanitation

### ISSUE THREAD

**Issue by Unthrottled** [waifu-motivator/waifu-motivator-plugin#264]
Looks like somebody was being cheeky and set the `Idle Timeout` to `0` which caused this:

https://sentry.io/share/issue/1700ae7dbc184ffc8f399e4dc591f2d0/

**Additional Info**

Additional Info | None
-- | --
App Name | PyCharm 2020.2.3 (Professional Edition)
Build Info | Build #PY-202.7660.27, built on October 6, 2020
Cores | 12
Current LAF | EVA: Misato Katsuragi
GC | ParNew,ConcurrentMarkSweep
JRE | Runtime version: 11.0.8+10-b944.34 amd64
Memory | 1970
Message | Error executing task zd.zero.waifu.motivator.plugin.WaifuMotivatorProject$$Lambda$1297/0x0000000101216440@58c1101b
Non-Bundled Plugins | indent-rainbow.indent-rainbow,io.acari.DDLCTheme,some.awesome,zd.zero.waifu-motivator-plugin,com.jetbrains.intellij.datalore,izhangzhihao.rainbow.brackets
Plugin Config | {   "isWaifuOfTheDayEnabled": false,   "isStartupMotivationEnabled": false,   "isStartupMotivationSoundEnabled": false,   "isUnitTesterMotivationEnabled": false,   "isUnitTesterMotivationSoundEnabled": false,   "isMotivateMeEnabled": false,   "isMotivateMeSoundEnabled": false,   "isSayonaraEnabled": false,   "isDisabledInDistractionFreeMode": false,   "isTaskMotivationEnabled": false,   "isTask...
Registry | <invalid>
System Info | Windows 10 10.0
VM | VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by zd-zero** [comment]
I'm now curious as to how it was updated? Was it manually changed from the configs?
We already have a `1` value minimum for Idle timeout:
https://github.com/zd-zero/waifu-motivator-plugin/blob/e0151a41a552f5568a8366f92dfc0240b0ab392d/src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java#L116

**Comment by Unthrottled** [comment]
There is nothing preventing them from modifying the `waifu-motivator-plugin.xml` file with the `0` value (I think) :thinking: :unamused:
