### ISSUE TITLE
Missing documentation in plugin marketplace 

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#284]
Release of [v1.4](https://github.com/waifu-motivator/waifu-motivator-plugin/releases/tag/v1.4) didn't properly include the documentation to the [plugin marketplace](https://plugins.jetbrains.com/plugin/13381-waifu-motivator).

Relates to #223

**Comment by Unthrottled** [comment]
![Whoops](https://media.giphy.com/media/3ohzdYJK1wAdPWVk88/giphy.gif)

Does it have anything to do with the [release notes](https://github.com/waifu-motivator/waifu-motivator-plugin/blob/master/buildSrc/src/main/kotlin/CreateReleaseNotes.kt#L20) build step (I can't remember off the top of my head :sweat_smile: )?

**Comment by zaerald** [comment]
I was thinking if I broke it ☠️ with #223
