### ISSUE TITLE
Allow users to exclude motivational content to not show up anymore

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#30]
Ability to ignore some motivational content when they show up. I'm thinking that this issue is not needed anymore when #17 is already implemented, maybe we can only enable this whenever there are no user motivation assets.

**Comment by Unthrottled** [comment]
Hey! I did this one without realizing it. You can set up a `Character Blacklist` in the [content](https://github.com/Unthrottled/AMII#content) settings.

![image](https://user-images.githubusercontent.com/15972415/106402448-1c6a6380-63ef-11eb-89b6-516197712727.png)
