### ISSUE TITLE
Pivot to discovering Waifus

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#324]
In before, the core functionality of this plugin is to have Waifu alerts for each event that has happened to the IDE. Since `v2.0` it's now moved to [AMII plugin](https://github.com/ani-memes/AMII/), not only is improved version of alert events and this also includes non-Waifu characters (i.e. robots, husbandos, heros, and much more!). This leaves the plugin to only functionality with Waifu-of-the-Day on startup. I plan to change this into a plugin that helps developers discover their new Waifu!

**Comment by Unthrottled** [comment]
There are so may good girls out there, and I know there are even more good ones out there I don't know exist. It makes it so hard to choose :sob: 

I am interested in seeing the next evolution of Waifu content delivery!

**Comment by zaerald** [comment]
Was thinking of using [Waifu List API](https://mywaifulist.moe) or create my own. Still computing the cost diff if I create/host my own assets (source repository). But will still develop an API for integrations. I plan to use Firebase Functions for discovering new Waifu. Thinking of having users to just state their Waifu preference (age, weight, height. 

So in line with this, once we have the API and also a web client, so they can provide their own Waifu. I'm thinking of expanding into having them in other platforms like Terminals that support images/gifs - on startup show an image of your Waifu, maybe similar to [fortune cli](https://en.wikipedia.org/wiki/Fortune_(Unix)), [cowsay](https://en.wikipedia.org/wiki/Cowsay). That is having `waifu-cli` 😂

 wdyt? Do you have any suggestions?

**Comment by Unthrottled** [comment]
Sounds cool! I built AMII's API using Amazon's API Gateway, Lambdas, & Dynamo, and I am still within the free tier usage (it was also a pain in the rear to set up). However, I also now have ~500MB of assets that users download overtime, and that cost the most. I think I'm up to about $1 a day in data transfer. That number keeps going up over time too :smile: :sweat_smile: :money_with_wings: 

Just as a fyi, you can have chromium browser windows int intellij, I've done that with the doki theme's welcome/update notification. There's also a [browser plugin too](https://plugins.jetbrains.com/plugin/16068-embeddedbrowser). So you have that option not tying you just to the IDE.

As for the CLI, option, you can do neat things with Hyper.js. Here is a plugin that launches a rocket [when you do a git push](https://github.com/bomanimc/gitrocket)

**Comment by zaerald** [comment]
Alright! Forgot about Git events! So we'll have a motivation for each git events, lol 😂. Hmmm, what if we can just use AMII here? 

I'll just try to compare different cloud providers, which offers a cost-effective approach for discovering new Waifu.

**Comment by zaerald** [comment]
Moved to discussion: https://github.com/waifu-motivator/waifu-motivator-plugin/discussions/329
