### ISSUE TITLE
Non-ASCII characters are not displayed correctly

### ISSUE THREAD

**Issue by janek515** [waifu-motivator/waifu-motivator-plugin#484]
**Describe the bug**
Non-ASCII characters are not displayed correctly

**To Reproduce**

1. Open IDE
2. See Waifu of the day dialog
3. Non-ascii characters in the description look like a mess

**Expected behaviour**

Non-ASCII characters displayed correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/37900649/205443894-bd6e42b0-4340-42b0-bae3-d056a6041272.png)

**Platform:**

 - OS: Windows 11
 - IDE WebStorm
 - IDE Version 2022.3
 - Version WMP 2.4.0

**Additional context**

My PC language is set to Polish, while my IDE is in English. Maybe this messes with encoding in some way

**Comment by Unthrottled** [comment]
I've seen similar issues related to this on the Windows platform in other places.

I might have some time later to take a look into it, thanks for taking the time to report the issue!

**Comment by Unthrottled** [comment]
Figured out the issue.

Step 1: Decode the description assets correctly (in utf-8).
Step 2: ???
Step 3: Profit! 🎉
